import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { supabaseServer } from "@/lib/supabase/server";
import AppShell from "@/components/AppShell";
import { Gauge } from "@/components/TerminalMockup";
import { NowDateLong, NowGreeting, UpcomingFriday } from "@/components/Now";
import { fetchMarketNews, newsTime } from "@/lib/news";
import WatchlistPanel from "./WatchlistPanel";
import ActivityFeed from "./ActivityFeed";

export const metadata: Metadata = {
  title: "Dashboard — HighStrike",
};


export default async function DashboardPage() {
  const supabase = await supabaseServer();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/signin?next=/dashboard");

  const { data: profile } = await supabase
    .from("profiles")
    .select("is_admin, name, avatar_url")
    .eq("id", user.id)
    .single();
  const isAdmin = Boolean(profile?.is_admin);

  const firstName = profile?.name || (user.email ?? "trader").split("@")[0];

  // Latest published weather report + its setup cards.
  const { data: weather } = await supabase
    .from("weather_reports")
    .select("report_date, volatility, opportunity, direction, summary, model")
    .order("report_date", { ascending: false })
    .limit(1)
    .maybeSingle();

  const { data: setupRows } = weather
    ? await supabase
        .from("setups")
        .select(
          "ticker, direction, justification, entry_criteria, price_target, time_frame, flow_score, status, current_pct, result_pct, symbols(name)"
        )
        .eq("report_date", weather.report_date)
        .order("flow_score", { ascending: false })
    : { data: null };

  const setups = (setupRows ?? []).map((s) => {
    const pct = s.status === "open" ? s.current_pct : s.result_pct;
    return {
      ticker: `$${s.ticker}`,
      name: (s.symbols as unknown as { name: string } | null)?.name ?? s.ticker,
      direction: s.direction === "long" ? "Long" : "Short",
      up: s.direction === "long",
      target: s.price_target,
      frame: s.time_frame,
      justification: s.justification,
      flow: s.flow_score,
      status: s.status as string,
      pct: pct as number | null,
    };
  });

  const marketNews = await fetchMarketNews();

  const reportLabel = weather
    ? new Date(`${weather.report_date}T12:00:00Z`).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        timeZone: "UTC",
      })
    : null;

  return (
    <AppShell
      email={user.email ?? ""}
      isAdmin={isAdmin}
      active="home"
      displayName={profile?.name}
      avatarUrl={profile?.avatar_url}
    >
      
          {/* Greeting */}
          <div className="anim-rise flex flex-col justify-between gap-3 sm:flex-row sm:items-end">
            <div>
              <p className="text-xs uppercase tracking-wider text-ink-3">
                <NowDateLong />
              </p>
              <h1 className="mt-1 font-display text-2xl font-bold sm:text-3xl">
                <NowGreeting />, {firstName}
              </h1>
            </div>
            <p className="rounded-full border border-accent/40 bg-panel px-3.5 py-1.5 text-xs text-ink-2">
              <span className="font-semibold text-accent">Beta</span> — daily reports
              and live watchlists are on; flow scanner is next
            </p>
          </div>

          {/* Weather strip */}
          <section className="anim-rise mt-8" style={{ "--rise-delay": "80ms" } as React.CSSProperties}>
            <div className="flex items-baseline justify-between">
              <h2 className="font-display text-sm font-semibold uppercase tracking-wide text-ink-2">
                {reportLabel ? `Weather report — ${reportLabel}` : "Weather report"}
              </h2>
              <span className="text-[10px] uppercase tracking-wider text-ink-3">
                {weather
                  ? weather.model === "heuristic"
                    ? "Generated from market data"
                    : "Generated by HighStrike AI"
                  : "Pending"}
              </span>
            </div>
            {weather ? (
              <>
                <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3">
                  <Gauge label="Volatility" value={weather.volatility} />
                  <Gauge label="Opportunity" value={weather.opportunity} />
                  <Gauge label="Direction" value={weather.direction} />
                </div>
                {weather.summary && (
                  <p className="mt-3 rounded-xl border border-line bg-panel px-4 py-3 text-sm leading-relaxed text-ink-2">
                    {weather.summary}
                  </p>
                )}
              </>
            ) : (
              <p className="mt-3 rounded-xl border border-line bg-panel px-4 py-6 text-center text-sm text-ink-3">
                Today&apos;s report generates before the open (8:30 AM ET).
              </p>
            )}
          </section>

          <div className="mt-10 grid gap-8 xl:grid-cols-3">
            {/* Setups */}
            <section className="anim-rise xl:col-span-2" style={{ "--rise-delay": "160ms" } as React.CSSProperties}>
              <div className="flex items-baseline justify-between">
                <h2 className="font-display text-sm font-semibold uppercase tracking-wide text-ink-2">
                  {reportLabel ? `Setups — ${reportLabel}` : "Setups"}
                </h2>
                <span className="text-[10px] uppercase tracking-wider text-ink-3">
                  Market commentary — not investment advice
                </span>
              </div>
              {setups.length === 0 && (
                <p className="mt-3 rounded-xl border border-line bg-panel px-4 py-6 text-center text-sm text-ink-3">
                  No setups published yet — the next batch lands before the open.
                </p>
              )}
              <div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {setups.map((s) => (
                  <div
                    key={s.ticker}
                    className="card-lift flex flex-col rounded-2xl border border-line bg-panel p-5 hover:border-accent/40 hover:shadow-lg"
                  >
                    <div className="flex items-center justify-between">
                      <Link
                        href={`/symbol/${s.ticker.replace("$", "")}`}
                        className="font-display text-lg font-bold transition hover:text-accent"
                      >
                        {s.ticker}
                      </Link>
                      <span
                        className={`font-mono-nums text-xs ${s.up ? "text-up" : "text-down"}`}
                      >
                        {s.up ? "▲" : "▼"} {s.direction}
                      </span>
                    </div>
                    <div className="mt-0.5 flex items-center justify-between">
                      <p className="text-xs text-ink-3">{s.name}</p>
                      <span
                        className={`font-mono-nums text-[11px] ${
                          s.pct == null
                            ? "text-ink-3"
                            : s.pct >= 0
                              ? "text-up"
                              : "text-down"
                        }`}
                      >
                        {s.status === "target_hit" && "✓ Target hit "}
                        {s.status === "stopped" && "✕ Stopped "}
                        {s.status === "expired" && "Expired "}
                        {s.pct != null &&
                          `${s.pct >= 0 ? "+" : ""}${s.pct.toFixed(2)}%${s.status === "open" ? " so far" : ""}`}
                      </span>
                    </div>
                    <p className="mt-3 flex-1 text-xs leading-relaxed text-ink-2">
                      {s.justification}
                    </p>
                    <dl className="mt-4 space-y-1.5 border-t border-line pt-3 text-xs">
                      <div className="flex justify-between">
                        <dt className="text-ink-3">Target</dt>
                        <dd className="font-mono-nums text-accent">{s.target}</dd>
                      </div>
                      <div className="flex justify-between">
                        <dt className="text-ink-3">Time frame</dt>
                        <dd className="font-mono-nums">{s.frame}</dd>
                      </div>
                      <div className="flex justify-between">
                        <dt className="text-ink-3">Nearest expiry</dt>
                        <dd className="font-mono-nums">
                          <UpcomingFriday />
                        </dd>
                      </div>
                      <div className="flex items-center justify-between">
                        <dt className="text-ink-3">Flow score</dt>
                        <dd className="flex items-center gap-2">
                          <span className="h-1.5 w-12 overflow-hidden rounded-full bg-panel-2" aria-hidden="true">
                            <span
                              className="block h-full rounded-full bg-accent"
                              style={{ width: `${s.flow}%` }}
                            />
                          </span>
                          <span className="font-mono-nums">{s.flow}</span>
                        </dd>
                      </div>
                    </dl>
                  </div>
                ))}
              </div>

              {/* Watchlist — live */}
              <WatchlistPanel userId={user.id} />
            </section>

            {/* Right rail */}
            <section className="anim-rise" style={{ "--rise-delay": "240ms" } as React.CSSProperties}>
              <div className="flex items-baseline justify-between">
                <h2 className="font-display text-sm font-semibold uppercase tracking-wide text-ink-2">
                  Activity
                </h2>
                <span className="text-[10px] uppercase tracking-wider text-ink-3">
                  Live feed
                </span>
              </div>
              <ActivityFeed />

              {marketNews.items.length > 0 && (
                <>
                  <div className="mt-8 flex items-baseline justify-between">
                    <h2 className="font-display text-sm font-semibold uppercase tracking-wide text-ink-2">
                      Market news
                    </h2>
                    <span className="text-[10px] uppercase tracking-wider text-ink-3">
                      Live headlines
                    </span>
                  </div>
                  <ul className="mt-3 divide-y divide-line rounded-2xl border border-line bg-panel">
                    {marketNews.items.map((n) => (
                      <li key={n.url}>
                        <a
                          href={n.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="block px-5 py-3 transition hover:bg-panel-2"
                        >
                          <p className="text-sm text-ink">{n.headline}</p>
                          <p className="mt-0.5 text-xs text-ink-3">
                            {n.source} · {newsTime(n.datetime)}
                          </p>
                        </a>
                      </li>
                    ))}
                  </ul>
                </>
              )}

              <div className="mt-6 rounded-2xl border border-line bg-panel p-6">
                <h3 className="font-display text-sm font-semibold">
                  While you wait for your cohort
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-ink-2">
                  The blog covers the process behind every card — expectancy,
                  sizing, and how the AI reads the market each morning.
                </p>
                <div className="mt-4 flex gap-3">
                  <Link
                    href="/blog"
                    className="rounded-lg bg-accent px-4 py-2 font-display text-xs font-semibold text-bg transition hover:bg-accent-2"
                  >
                    Read the blog
                  </Link>
                  <Link
                    href="/results"
                    className="rounded-lg border border-line-strong px-4 py-2 font-display text-xs font-semibold text-ink-2 transition hover:border-accent/50 hover:text-accent"
                  >
                    Scoreboard
                  </Link>
                </div>
              </div>
            </section>
          </div>
    </AppShell>
  );
}
