"use client";

// Public-site fragments driven by Admin ▸ Site settings, with built-in
// defaults so the site renders identically when nothing has been customized.

import { useSiteSetting, SITE_DEFAULTS } from "@/lib/siteContent";
import { DateOffset, NowMonth } from "@/components/Now";

export function HeroStatBadges() {
  const badges = useSiteSetting("hero_badges", SITE_DEFAULTS.hero_badges);
  const items = [
    { value: badges.traders, label: "traders" },
    { value: badges.countries, label: "countries" },
  ];
  return (
    <div className="mt-7 flex flex-wrap items-center justify-center gap-3">
      {items.map((b) => (
        <span
          key={b.label}
          className="inline-flex items-center gap-2 rounded-full border border-line bg-panel px-3.5 py-1.5 text-sm text-ink-2"
        >
          <span className="h-1.5 w-1.5 rounded-full bg-accent" aria-hidden="true" />
          <span className="font-display font-semibold text-ink">{b.value}</span>
          {b.label}
        </span>
      ))}
    </div>
  );
}

export function BonusLine() {
  const custom = useSiteSetting("hero_bonus", SITE_DEFAULTS.hero_bonus);
  if (custom) {
    return <p className="text-xs text-ink-3">{custom}</p>;
  }
  return (
    <p className="text-xs text-ink-3">
      *BONUS: <NowMonth /> registrants get FREE access to HighStrike Trading School ($2,995
      value)
    </p>
  );
}

export function ScoreboardStats() {
  const { stats } = useSiteSetting("scoreboard", SITE_DEFAULTS.scoreboard);
  return (
    <div className="mt-12 grid w-full max-w-3xl grid-cols-1 gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-3">
      {stats.map((s) => (
        <div key={s.label} className="bg-panel px-6 py-8">
          <p className="font-display text-4xl font-bold text-accent">{s.value}</p>
          <p className="mt-1 text-xs uppercase tracking-wider text-ink-3">{s.label}</p>
        </div>
      ))}
    </div>
  );
}

export function ScoreboardTrades() {
  const { trades } = useSiteSetting("scoreboard", SITE_DEFAULTS.scoreboard);
  return (
    <div className="mt-6 grid w-full max-w-3xl gap-4 sm:grid-cols-2">
      {trades.map((t) => (
        <div
          key={t.ticker}
          className="flex items-center justify-between rounded-2xl border border-line bg-panel px-6 py-5"
        >
          <div className="text-left">
            <p className="text-xs text-ink-3">
              <DateOffset days={-Math.abs(t.daysAgo)} />
            </p>
            <p className="font-display text-xl font-bold">{t.ticker}</p>
            <p className="mt-0.5 inline-flex items-center gap-1.5 text-xs text-ink-2">
              <span className="h-1.5 w-1.5 rounded-full bg-up" aria-hidden="true" />
              {t.status}
            </p>
          </div>
          <p className="font-mono-nums text-2xl text-up">{t.result}</p>
        </div>
      ))}
    </div>
  );
}

const DEFAULT_LEGAL = [
  "The information provided by HighStrike and HighStrike AI is for informational and educational purposes only and should not be considered financial, investment, or trading advice. HighStrike does not make recommendations to buy or sell any securities, assets, or financial instruments. All trade ideas, analysis, and insights generated by our AI are intended solely as market commentary and should not be relied upon as the basis for any investment decision.",
  "HighStrike AI is intended to be a time saving tool which simplifies data collection and analysis, and should not be a replacement for due diligence and risk management. You should not rely on HighStrike AI to make your trading decisions.",
  "Trading and investing involve substantial risk, including the possible loss of principal. Past performance is not indicative of future results. You should conduct your own research and consult with a qualified financial advisor before making any investment decisions.",
  "HighStrike and its operators are not responsible for any trading losses, financial decisions, or damages that may result from the use of our platform or reliance on any information provided.",
];

export function LegalParagraphs() {
  const custom = useSiteSetting("legal_disclaimer", SITE_DEFAULTS.legal_disclaimer);
  const paragraphs = custom.length ? custom : DEFAULT_LEGAL;
  return (
    <>
      {paragraphs.map((p, i) => (
        <p key={i}>{p}</p>
      ))}
    </>
  );
}
